# when running hexo in a subdirectory (e.g. domain.tld/blog), remove leading slashes ( "/archives" -> "archives" )

version: 3.0
# Place your favicon.ico to /source directory.
favicon: /favicon.ico

# Set default keywords (Use a comma to separate)
keywords: Acheron,blog,博客,代码,技术,书法,读书

# Code Highlight theme
# Available value: normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal


menu:
  首页: /
  读书: /myblogs/read
  书法: /myblogs/shufa
  代码: /myblogs/code
  生活: /myblogs/life
  我是: /myblogs/about




# Static files
#vendors: vendors
css: css
js: js
images: images

# Miscellaneous, enter the tracking ID for your Google Analytics
google_analytics: 
